source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!

project 'Cell-Rx'
use_frameworks!

target 'Cell-Rx_Example' do
  pod 'Cell+Rx', :path => '../'
  pod 'RxCocoa',    '~> 3.0.0.alpha.1'
end

target 'Cell-Rx_Tests' do
  pod 'Cell+Rx', :path => '../'  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
    end
  end
end
